export const copy = {
  en: {
    status: ["Open", "Taken", "Submitted", "Approved", "Disputed", "Paid", "Refunded"],
    steps: ["Open", "Taken", "Submitted", "Approved", "Paid"],
    defaultCriteria: "Summarize the article in one paragraph. Mention X and Y.",
    chainReadFailed: "Chain read failed",
    connectFirst: "Connect a wallet first.",
    switchFirst: "Switch to HSKChain Testnet first.",
    reverted: "Transaction reverted",
    confirmed: "confirmed on HSKChain.",
    invalidBounty: "Enter a positive amount, criteria and deadline.",
    createAction: "Create bounty",
    approveAction: "Approve token",
    approvalReverted: "Token approval reverted",
    writeSubmission: "Write a submission first.",
    submitAction: "Submit work",
    storeFailed: "Submission store returned HTTP",
    hashDiffers: "Stored content hash differs",
    brandTag: "AI BOUNTY ESCROW",
    network: "HSKChain Testnet",
    switchLanguage: "中文",
    eyebrow: "CLEAR TERMS. TRANSPARENT PAYMENTS.",
    heroLine1: "Work gets verified.",
    heroLine2: "Payment gets released.",
    heroDescription: "Post a bounty with clear acceptance criteria. An AI agent can do the work. An AI reviewer checks it. The reward stays locked on chain until the challenge window closes.",
    heroPills: ["◈ On-chain escrow", "✦ AI verification", "◷ 60s challenge window"],
    flowTitle: "HOW A BOUNTY MOVES",
    flow: [
      ["Fund", "Lock demo USDT in escrow"],
      ["Deliver", "Human or agent submits proof"],
      ["Verify", "AI scores against your criteria"],
      ["Release", "Anyone calls claim after 60s"],
    ],
    deploymentNeeded: "Deployment needed: set NEXT_PUBLIC_TOKEN_ADDRESS and NEXT_PUBLIC_ESCROW_ADDRESS in the root .env, then restart the web server.",
    wrongChain: "Your wallet is on another chain.",
    switchChain: "Switch to HSKChain Testnet",
    workspaceKicker: "THE WORKSPACE",
    workspaceTitle: "Build trust into every task.",
    balance: "YOUR DEMO BALANCE",
    mintAction: "Mint demo tokens",
    mintButton: "+ Get 1,000 demo USDT",
    newBounty: "NEW BOUNTY",
    postTask: "Post a task",
    reward: "Reward",
    rewardHint: "mUSDT · demo token",
    criteria: "Acceptance criteria",
    criteriaHint: "Be specific about what passes",
    originalContentNote: "",
    deadline: "Deadline",
    deadlineHint: "Minutes from now",
    confirmWallet: "Confirm in wallet…",
    lockFunds: "Lock funds & create bounty",
    createNote: "Your wallet approves an exact amount, then locks it in the escrow contract.",
    live: "LIVE ON HSKCHAIN",
    bounties: "Bounties",
    refresh: "Refresh bounties",
    noBounties: "No bounties yet",
    firstTask: "Fund the first task to start the flow.",
    bounty: "BOUNTY",
    taskDetails: "Task details",
    poster: "POSTER",
    worker: "WORKER",
    sydneyTime: "Sydney time",
    submission: "Submission",
    openWork: "Open submitted work ↗",
    contentHash: "Content hash",
    aiReview: "AI REVIEW",
    reasonVerified: "✓ Reason matches on-chain hash",
    reasonMismatch: "⚠ Reason hash does not match chain",
    nextAction: "Next action",
    challengeWindow: "CHALLENGE WINDOW",
    readyToClaim: "Ready to claim",
    disputeBefore: "The poster may dispute before this timer ends.",
    anyoneRelease: "Anyone can release the escrowed reward to the worker.",
    acceptAction: "Accept bounty",
    acceptButton: "Accept this bounty ↗",
    submissionPlaceholder: "Paste your completed work here…",
    submitButton: "Submit work ↗",
    waitingVerifier: "Waiting for the AI verifier to review the submitted work.",
    releaseAction: "Release payment",
    releaseButton: "Release payment to worker ↗",
    disputeAction: "Open dispute",
    disputeButton: "Dispute AI verdict",
    refundAction: "Refund",
    refundButton: "Refund expired bounty",
    disputedNote: "Disputed. The configured arbiter must resolve this on chain.",
    closedNote: "This bounty is closed. The chain records the final transfer.",
    escrowContract: "ESCROW CONTRACT",
    viewTransaction: "View transaction ↗",
    demoTag: "· HACKATHON DEMO",
    demoDisclaimer: "Demo token has no value. AI judgments are reviewable and may be disputed.",
    explorer: "HSKChain Explorer ↗",
  },
  zh: {
    status: ["待接单", "进行中", "待验收", "争议期", "争议中", "已放款", "已退款"],
    steps: ["已发布", "已接单", "已提交", "已验收", "已放款"],
    defaultCriteria: "用一段中文说明链上托管如何保障自由职业者收款，并写明：发布者可以在 60 秒争议期内提出异议，期满后任何人都能触发放款。",
    chainReadFailed: "读取链上数据失败",
    connectFirst: "请先连接钱包。",
    switchFirst: "请先将钱包切换到 HSKChain 测试网。",
    reverted: "链上交易未成功",
    confirmed: "已在 HSKChain 确认。",
    invalidBounty: "请填写大于 0 的赏金、验收标准和截止时间。",
    createAction: "发布悬赏",
    approveAction: "授权测试币",
    approvalReverted: "测试币授权未成功",
    writeSubmission: "请先填写交付内容。",
    submitAction: "提交交付内容",
    storeFailed: "保存交付内容失败，HTTP 状态码",
    hashDiffers: "保存后的内容哈希不一致",
    brandTag: "AI 验收悬赏",
    network: "HSKChain 测试网",
    switchLanguage: "English",
    eyebrow: "任务标准明确，赏金流向透明",
    heroLine1: "先锁定酬劳。",
    heroLine2: "验收通过，依约放款。",
    heroDescription: "发布任务时，先把测试币存入链上托管合约。接单者交付后，AI 按事先写好的标准验收。通过后留出 60 秒争议期，期满即可放款。",
    heroPills: ["◈ 链上托管", "✦ AI 验收", "◷ 60 秒争议期"],
    flowTitle: "一笔悬赏如何完成",
    flow: [
      ["锁定赏金", "发布时将测试币存入合约"],
      ["提交交付", "由人或 AI 智能体完成任务"],
      ["按标准验收", "AI 对照发布时的要求评分"],
      ["完成放款", "争议期结束后可触发放款"],
    ],
    deploymentNeeded: "尚未配置合约地址：请在项目根目录的 .env 中设置 NEXT_PUBLIC_TOKEN_ADDRESS 和 NEXT_PUBLIC_ESCROW_ADDRESS，然后重启网页服务。",
    wrongChain: "钱包当前连接的是其他网络。",
    switchChain: "切换到 HSKChain 测试网",
    workspaceKicker: "开始使用",
    workspaceTitle: "从发布任务到验收放款，进度一目了然。",
    balance: "我的测试币余额",
    mintAction: "领取测试币",
    mintButton: "+ 领取 1,000 测试 mUSDT",
    newBounty: "发布新悬赏",
    postTask: "把任务说清楚",
    reward: "赏金",
    rewardHint: "mUSDT · 无价值测试币",
    criteria: "验收标准",
    criteriaHint: "写清楚怎样才算完成",
    originalContentNote: "任务要求和 AI 验收理由按原文展示，以便核对链上记录。",
    deadline: "截止时间",
    deadlineHint: "从现在起多少分钟",
    confirmWallet: "请在钱包中确认…",
    lockFunds: "锁定赏金并发布",
    createNote: "钱包会先授权本次所需的确切金额，再把测试币锁入托管合约。可能需要确认两笔交易。",
    live: "HSKCHAIN 链上任务",
    bounties: "悬赏列表",
    refresh: "刷新悬赏列表",
    noBounties: "还没有悬赏",
    firstTask: "发布第一笔任务，开启完整演示。",
    bounty: "悬赏",
    taskDetails: "任务详情",
    poster: "发布者",
    worker: "接单者",
    sydneyTime: "悉尼时间",
    submission: "交付记录",
    openWork: "查看交付内容 ↗",
    contentHash: "内容哈希",
    aiReview: "AI 验收结果",
    reasonVerified: "✓ 验收理由与链上哈希一致",
    reasonMismatch: "⚠ 验收理由与链上哈希不一致",
    nextAction: "下一步",
    challengeWindow: "争议期倒计时",
    readyToClaim: "可发起放款",
    disputeBefore: "倒计时结束前，发布者可以对 AI 验收结果提出异议。",
    anyoneRelease: "争议期已结束，任何人都可以触发向接单者放款。",
    acceptAction: "接下悬赏",
    acceptButton: "接下这个任务 ↗",
    submissionPlaceholder: "在这里填写完整的交付内容…",
    submitButton: "提交交付内容 ↗",
    waitingVerifier: "交付已上链，正在等待 AI 按验收标准审核。",
    releaseAction: "向接单者放款",
    releaseButton: "向接单者放款 ↗",
    disputeAction: "提出争议",
    disputeButton: "对 AI 验收提出异议",
    refundAction: "领取退款",
    refundButton: "取回逾期赏金",
    disputedNote: "此任务存在争议，需由指定仲裁账户在链上处理。",
    closedNote: "任务已结束，最终转账结果已记录在链上。",
    escrowContract: "托管合约",
    viewTransaction: "查看链上交易 ↗",
    demoTag: "· 黑客松演示",
    demoDisclaimer: "mUSDT 是没有实际价值的测试币。AI 验收结果可以核对，发布者也可以在争议期内提出异议。",
    explorer: "查看 HSKChain 区块浏览器 ↗",
  },
} as const;

export type PageLocale = keyof typeof copy;
